

try:
    x = 2
    print(x+y)
except Exception as e:
    print('OOPS, erro de x: ', e)
